### ISSUE TITLE
Add Tiered Skins 

### ISSUE THREAD

**Issue by koelol** [rico-vz/Hweis-Brush#1]
Immortalized Legend Ahri missing.

Would it be possible to add it? As well as animated splash arts like DJ Sona, Gun Goddess Miss Fortune, and Immortalized Legend Ahri signature version?

**Comment by rico-vz** [comment]
> Immortalized Legend Ahri missing.
> 
> Would it be possible to add it? As well as animated splash arts like DJ Sona, Gun Goddess Miss Fortune, and Immortalized Legend Ahri signature version?

Skins like DJ Sona and Gun Goddess MF are automatically animated when set.
I'll be adding tiered skins like K/DA All Out Seraphine & Immortalized Legend Ahri in a future update, thanks for pointing out that they were missing.

**Comment by rico-vz** [comment]
@koelol This has been fixed in the latest release
